steps:
  protecodeExecuteScan:
    group: "2743"
    serverUrl: "https://qa"
    userAPIKey: "AAAV"
    fetchUrl: "https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-minirootfs-3.19.0-x86_64.tar.gz"
