steps:
  protecodeExecuteScan:
    group: "2743"
    serverUrl: "https://qa.bdba.tools.sap"
    userAPIKey: "AAAVw02ZjkVPRo0Dzs10fTadAXi2jZ9Nb8ZmY7yVPImCZ0PY"
    fetchUrl: "https://dl-cdn.alpinelinux.org/alpine/latest-stable/releases/x86_64/alpine-minirootfs-3.19.0-x86_64.tar.gz"
